# This workflow will install dependencies and run pytest

name: Run-Pytest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run pytest
    steps:
    - uses: actions/checkout@v4
    - name: Install requirements
      run: pip install -r requirements-dev.txt
    - name: Run tests
      run: pytest
